// Native animated seed quads retain their bones, visibility and encoded size.
// The two local textures are generated by Tools/Smoke/generate_smoke_atlas.py.
Shader "AeroStadium/NativeSmokeCloud"
{
    Properties
    {
        _Mask0Tex("Masque source conservé",2D)="black" {}
        _FireTex("Texture source conservée",2D)="white" {}
        _TransU("Animation native secondaire",Float)=0
        _Mask0UVTranslateU("Animation native U",Float)=0
        _Mask0UVTranslateV("Animation native V",Float)=0
        _Mask0UVScaleU("Échelle native U",Float)=1
        _Mask0UVScaleV("Échelle native V",Float)=1
        [HideInInspector] _NativeSmokeBillboard("Contrôles natifs",Float)=1
        _BillboardScale("Échelle du modèle",Float)=1
        [HideInInspector] _CloudWorldOffset("Ancrage mondial du nuage",Vector)=(0,0,0,0)
        _PuffRadiusScale("Rayon du nuage",Float)=.55
        _Opacity("Densité",Range(0,1))=.48
        _BaseColor("Fumée claire",Color)=(.85,.8204,.61456,1)
        _LayerColor("Fumée dense",Color)=(.59696,.55006,.26409,1)
        [NoScaleOffset] _CloudAtlas("Volume de fumée local",2D)="black" {}
        [NoScaleOffset] _CloudFlow("Volutes périodiques locales",2D)="gray" {}
        _CloudFlowSpeed("Vitesse des volutes",Range(0,2))=.7
        _CloudDetail("Detail des volutes",Range(0,1))=.7
    }
    SubShader
    {
        Tags { "RenderPipeline"="UniversalPipeline" "Queue"="Transparent" "RenderType"="Transparent" }
        Pass
        {
            Tags { "LightMode"="UniversalForward" }
            Blend SrcAlpha OneMinusSrcAlpha
            ZWrite Off
            ZTest LEqual
            Cull Off
            HLSLPROGRAM
            #pragma vertex Vert
            #pragma fragment Frag
            #pragma multi_compile_fog
            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"
            TEXTURE2D(_CloudAtlas); SAMPLER(sampler_CloudAtlas);
            TEXTURE2D(_CloudFlow); SAMPLER(sampler_CloudFlow);
            CBUFFER_START(UnityPerMaterial)
            float4 _BaseColor,_LayerColor,_CloudWorldOffset;
            float _BillboardScale,_PuffRadiusScale,_Opacity,_Mask0UVTranslateU,_TransU;
            float _CloudFlowSpeed,_CloudDetail;
            CBUFFER_END
            struct A { float4 positionOS:POSITION; float4 controls:TEXCOORD4; float2 life:TEXCOORD5; };
            struct V
            {
                float4 positionCS:SV_POSITION;
                float2 puffUv:TEXCOORD0;
                float seed:TEXCOORD1;
                float variation:TEXCOORD2;
                half fog:TEXCOORD3;
                float2 tile:TEXCOORD4;
                half lifeAlpha:TEXCOORD5;
            };
            V Vert(A a)
            {
                V v;
                float3 world=TransformObjectToWorld(a.positionOS.xyz);
                // Connector vertices have RG=128/255. Seed corners have RG=0/1.
                // Classify here so interpolation never erases the seed center.
                v.seed=step(.49,max(abs(a.controls.r-.5),abs(a.controls.g-.5)));
                float2 offset=(a.controls.rg*2-1)*a.controls.b*_BillboardScale*_PuffRadiusScale*v.seed;
                world+=UNITY_MATRIX_I_V._m00_m10_m20*offset.x+UNITY_MATRIX_I_V._m01_m11_m21*offset.y;
                world+=_CloudWorldOffset.xyz;
                v.positionCS=TransformWorldToHClip(world);
                v.puffUv=a.controls.rg;
                // B is invariant over the four corners and survives all clips.
                // A stable card identity avoids random popping during bone motion.
                // Persistent authored cards have an explicit lifetime channel.
                // Native cards retain their original stable B-based identity.
                float authored=step(.5,a.life.y);
                v.variation=lerp(a.controls.b,a.controls.a,authored)*73;
                v.lifeAlpha=lerp(1,saturate(a.life.x),authored);
                float cell=floor(frac(v.variation*.754877666)*16);
                v.tile=float2(fmod(cell,4),floor(cell*.25));
                v.fog=ComputeFogFactor(v.positionCS.z);
                return v;
            }
            half4 Frag(V v):SV_Target
            {
                clip(v.seed-.5);
                float2 uv=v.puffUv;
                // This is a rectangular safety gate, never the cloud silhouette.
                // The integrated atlas supplies the irregular connected plume.
                float edgeDistance=min(min(uv.x,1-uv.x),min(uv.y,1-uv.y));
                half border=smoothstep(0,.045,edgeDistance);
                float time=_Time.y*_CloudFlowSpeed;
                float2 phase=float2(v.variation*.137,v.variation*.297);
                phase+=float2(_TransU,_Mask0UVTranslateU)*.025;
                float2 flowUv=uv*1.16+phase+time*float2(.023,-.034);
                half4 flow=SAMPLE_TEXTURE2D(_CloudFlow,sampler_CloudFlow,flowUv);
                half4 eddy=SAMPLE_TEXTURE2D(_CloudFlow,sampler_CloudFlow,flowUv*1.87+time*float2(-.016,.027));
                // Continuous, bounded curl advection rolls the folds without
                // scrolling an atlas tile across its neighbors or looping frames.
                float2 displacement=((flow.rg*2-1)*.028+(eddy.rg*2-1)*.011)*border;
                float2 localUv=clamp(uv+displacement,.002,.998);
                half4 cloud=SAMPLE_TEXTURE2D(_CloudAtlas,sampler_CloudAtlas,(v.tile+localUv)*.25);
                half density=cloud.r;
                half detail=(flow.b-.5)*.16+(eddy.a-.5)*.26;
                density=saturate(density*(1+detail*_CloudDetail));
                half alpha=density*_Opacity*border*v.lifeAlpha;
                clip(alpha-.002);
                // GB hold projected volume normals; A holds baked self-shadow.
                // Fine eddies animate the thickness, while light follows billows.
                half2 normalXY=cloud.gb*2-1;
                half directional=dot(normalXY,half2(-.35,.55));
                half shadow=saturate((1-cloud.a)*1.12-directional*.28);
                half denseMix=saturate(shadow*.78+density*.16-detail*.18);
                half3 color=lerp(_BaseColor.rgb,_LayerColor.rgb,denseMix);
                color*=.94+.06*cloud.a;
                return half4(MixFog(color,v.fog),alpha);
            }
            ENDHLSL
        }
    }
}
